spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: aron
    password: 123
    url: jdbc:postgresql://localhost:5432/ReadOn
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: false
        format_sql: true
    servlet:
      multipart:
        max-file-size:
          10MB
server:
  port: 8090